### ISSUE TITLE
Warning: Undefined array key "_dfrps_cpt_last_update_time_completed"

### ISSUE THREAD

**Issue by EricBusch** [datafeedr/datafeedr-product-sets#24]
Getting the following error report from a customer:

> After adding products to new product sets I get the following message:
> 
> Warning: Undefined array key "_dfrps_cpt_last_update_time_completed" in ~/wp-content/plugins/datafeedr-product-sets/classes/class-dfrps-cpt.php on line 1143 Warning: Trying to access array offset on value of type null in ~/wp-content/plugins/datafeedr-product-sets/classes/class-dfrps-cpt.php on line 1143 This Product Set has never been imported.

Not sure if it's related to 1.3.16 or goes back further. Can you have a look when you get a chance?

**Comment by growdev** [comment]
The last update time completed is correctly set in meta and when pulled [here](https://github.com/datafeedr/datafeedr-product-sets/blame/master/classes/class-dfrps-cpt.php#L1135) it is 0 if the Product Set has never been imported. 

I used the same line of code [here](https://github.com/datafeedr/datafeedr-product-sets/blame/master/classes/class-dfrps-cpt.php#L1143), but in the line before `$meta` is replaced by the contents of `_dfrps_cpt_previous_update_info` which is an empty array for a Product Set that has never been imported.
